name: publish-to-aur

on:
  push:
    branch:
      - "main"

jobs:
  bindNgrind:
    runs-on: ubuntu-latest
    steps:
      - name: Load ssh-key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: aur
          known_hosts: ${{ secrets.KNOWN_HOST }}
          if_key_exists: fail
      
      - name: verify ssh-key
        run: |
          ssh-keyscan aur.archlinux.org
          
      - name: Checkout this fine duck
        uses: actions/checkout@v3

      - name: Git clone a package from aur repo
        run: |
          ssh-keyscan aur.archlinux.org
          pwd
          git clone ssh://aur@aur.archlinux.org/nepali-calendar-gtk-git.git
          pwd
          ls
          cd nepali-calendar-gtk-git
          ls -la

